db:
    build: ./mysql
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=mypasswordroot
    volumes:
      - /data/mysql:/var/lib/mysql

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - web
  links:
    - app:app

app:
    build: ./app
    environment:
      NODE_ENV: production
    ports:
      - '8888:8888'
    links:
      - 'db:db'